FROM ruby:3.4.9

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential \
      git \
      libpq-dev \
      postgresql-client \
      libvips \
      pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

COPY Gemfile ./

RUN bundle install 

COPY  . .

EXPOSE 3000

CMD ["./bin/rails", "server", "-b", "0.0.0.0"]
